const Photo=[
    {
        id:1,
        img:'./Images/pokhara.jpg',
        name:'Pokhara'
    },
    {
        id:2,
        img:'./Images/kathmandu.jpg',
        name:"Kathmandu"
    },
    {
        id:3,
        img:'./Images/solukhumbu.jpg',
        name:"Solukhumbu"
    },
    {
        id:4,
        img:'./Images/chitwan.jpg',
        name:"Chitwan"
    },
    {
        id:5,
        img:'./Images/dharan.jpg',
        name:"Dharan"
    },
    {
        id:6,
        img:'./Images/dharan.jpg',
        name:"Dharan"
    },
    {
        id:7,
        img:'./Images/lumbini.jpg',
        name:"Lumbini"
    },
    {
        id:8,
        img:'./Images/illam.jpg',
        name:"Illam"
    }
]
export default Photo;